id: A8282CEA5
title: 'Wellspring of Bounty for the Fortunate: A Guru Yoga of the Three Family Lords'
type: translation
pechas:
- IAF1FD747
- I299E9C32
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:03.249746
  last_modified_at: 2023-01-04 12:01:03.249759
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  IAF1FD747/9000: A57F
  I299E9C32/46F0: A57F
